spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/travel_assistant
    username: postgres
    password: HOSPITAL3COURSE
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: super-secret-key-123456789-super-secret-key
  expiration-ms: 86400000

server:
  port: 8080
